# Generated by Django 5.1.3 on 2024-12-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('developer', 'Developer'), ('maintenance_company', 'Maintenance_Company'), ('technician', 'Technician')], default='developer', max_length=50),
        ),
    ]
